name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      
      
      
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/foertel/oidc-webfinger:${GITHUB_SHA::8}
      
      - name: Test Container
        timeout-minutes: 1
        run: |
          docker run -d --name webfinger -e OIDC_ISSUER_URL="https://example.org/" -p 80:80 ghcr.io/foertel/oidc-webfinger:${GITHUB_SHA::8}
          while [ "`docker inspect -f {{.State.Health.Status}} webfinger`" != "healthy" ]; do sleep 1; done
          curl -s http://localhost/.well-known/webfinger?resource=acct:example@example.org > /tmp/curl.txt && diff /tmp/curl.txt test/example-response.json || exit 1

      - name: 'Login to GitHub Container Registry'
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Docker Images
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/foertel/oidc-webfinger:${GITHUB_SHA::8}
          docker tag ghcr.io/foertel/oidc-webfinger:${GITHUB_SHA::8} ghcr.io/foertel/oidc-webfinger:latest
          docker push ghcr.io/foertel/oidc-webfinger:latest
    
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: build
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}